### PR TITLE
to_alternate: Switch back to main screen if into_raw_mode fails

### PR DESCRIPTION
**Pull request by andersk**

### CODE REVIEW

**Comment by TimonPost** [comment]
What is the motivation behind this change?

**Comment by zrzka** [comment]
I would guess cleanup? If I ask for alternate screen in raw mode and the function fails, I, as a user, do not want to end up in an inconsistent state like alternate & no raw. Which is not something I asked for. It should give me both or nothing.

**Comment by andersk** [comment]
Right now if you run any Crossterm application that does `to_alternate(true)` with stdin piped in from something other than a terminal, the `into_raw_mode` call fails, and you end up stuck in alternate screen mode even after the application exits, which is an annoying condition that this wrapper type was supposed to avoid.

**Comment by zrzka** [comment]
I'd merge this one as it's really useful and make the API / behavior more consistent.

**Comment by TimonPost** [comment]
Yea this is very useful, thanks for the explanation!

**Pull request merged**
